export const sponsorHeaders = [
  'Sponsor',
  'Sponsor Type',
  'Sponsor Group',
  'RTS ID',
  'LCRN',
  'No. Reset Studies 28Sep22',
  'No. Closure Studies 28Sep22',
  'No. Reset Studies 19Oct22',
  'No. Closure Studies 19Oct22',
  'No. Reset Studies 14Nov22',
  'No. Closure Studies 14Nov22',
  'No. Reset Studies 07Dec22',
  'No. Closure Studies 07Dec22',
  'No. Reset Studies 05Jan23',
  'No. Closure Studies 05Jan23',
  'No. Reset Studies 03Feb23',
  'No. Closure Studies 03Feb23',
  'No. Reset Studies 02Mar23',
  'No. Closure Studies 02Mar23',
  'No. Reset Studies 12Apr23',
  'No. Closure Studies 12Apr23',
  'No. Reset Studies 16May23',
  'No. Closure Studies 16May23',
  'No. Reset Studies 04Jul23',
  'No. Closure Studies 04Jul23',
  'No. Reset Studies 10Aug23',
  'No. Closure Studies 10Aug23',
  'No. Reset Studies 20Sep23',
  'No. Closure Studies 20Sep23',
  'No. Reset Studies',
  'No. Closure Studies',
  'Notes',
  'Contact 1',
  'Contact 2',
  'Contact 3',
  'Contact 4',
  'Contact 5',
  'Contact 6',
  'Contact 7',
  'bcc',
  'MM contacts',
  'Invalid or Zero Contacts',
  'MM Filter',
  'Zero Contacts',
] as const

export const ctuHeaders = [
  'CTU',
  'RTS ID',
  'No. Reset Studies 10May22',
  'No. Reset Studies 28Sep22',
  'No. Closure Studies 28Sep22',
  'No. Reset Studies 19Oct22',
  'No. Closure Studies 19Oct22',
  'No. Reset Studies 14Nov22',
  'No. Closure Studies 14Nov22',
  'No. Reset Studies 07Dec22',
  'No. Closure Studies 07Dec22',
  'No. Reset Studies 05Jan23',
  'No. Closure Studies 05Jan23',
  'No. Reset Studies 03Feb23',
  'No. Closure Studies 03Feb23',
  'No. Reset Studies 02Mar23',
  'No. Closure Studies 02Mar23',
  'No. Reset Studies 12Apr23',
  'No. Closure Studies 12Apr23',
  'No. Reset Studies 16May23',
  'No. Closure Studies 16May23',
  'No. Reset Studies 04Jul23',
  'No. Closure Studies 04Jul23',
  'No. Reset Studies 10Aug23',
  'No. Closure Studies 10Aug23',
  'No. Reset Studies',
  'No. Closure Studies',
  'Notes',
  'Contact 1',
  'Contact 2',
  'Contact 3',
  'Contact 4',
  'Contact 5',
  'MM contacts',
] as const

export const croHeaders = [
  'CRO',
  'RTS ID',
  'Category?',
  'No. Reset Studies 6Jun22',
  'No. Reset Studies 28Sep22',
  'No. Closure Studies 28Sep22',
  'No. Reset Studies 19Oct22',
  'No. Closure Studies 19Oct22',
  'No. Reset Studies 14Nov22',
  'No. Closure Studies 14Nov22',
  'No. Reset Studies 07Dec22',
  'No. Closure Studies 07Dec22',
  'No. Reset Studies 05Jan23',
  'No. Closure Studies 05Jan23',
  'No. Reset Studies 03Feb23',
  'No. Closure Studies 03Feb23',
  'No. Reset Studies 02Mar23',
  'No. Closure Studies 02Mar23',
  'No. Reset Studies 12Apr23',
  'No. Closure Studies 12Apr23',
  'No. Reset Studies 16May23',
  'No. Closure Studies 16May23',
  'No. Reset Studies 04Jul23',
  'No. Closure Studies 04Jul23',
  'No. Reset Studies 10Aug23',
  'No. Closure Studies 10Aug23',
  'No. Reset Studies',
  'No. Closure Studies',
  'Notes',
  'Contact 1',
  'Contact 2',
  'Contact 3',
  'Contact 4',
  'Contact 5',
  'bcc',
  'MM contacts',
] as const

export const contactHeaders = [
  'Contact 1',
  'Contact 2',
  'Contact 3',
  'Contact 4',
  'Contact 5',
  'Contact 6',
  'Contact 7',
]

export const reportHeaders = ['Organisation Name', 'Organisation Role', 'RTS Identifier', ...contactHeaders]
