name: Pull Requests

on:
  pull_request:
    branches:
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  # Install dependencies
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/install-cache
      - uses: ./.github/actions/turbo-cache
      - name: Install
        run: npm ci --no-audit --no-fund

  # Build project
  build:
    name: Build
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/install-cache
      - uses: ./.github/actions/build-cache
      - name: Build
        run: |
          touch .env.local
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env.local
          echo NEXT_PUBLIC_APP_ENV=${{ vars.APP_ENV }} >> .env.local
          npx turbo run build --cache-dir=".turbo"

  # Code quality checks
  quality-checks:
    name: Lint
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/install-cache
      - uses: ./.github/actions/build-cache
      - name: Quality check
        run: npx turbo run lint --cache-dir=".turbo"

  # Unit tests
  unit-tests:
    name: Unit tests
    permissions: write-all
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/install-cache
      - uses: ./.github/actions/build-cache
      - name: Unit tests
        run: |
          npx turbo run test:ci --cache-dir=".turbo"
      - name: Unit tests coverage comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          title: Unit tests coverage
          multiple-files: |
            Web App, apps/web/coverage/coverage-summary.json
            Ingest App, apps/ingest/coverage/coverage-summary.json
            UI Package, packages/ui/coverage/coverage-summary.json
