name: Pull Requests

on:
  pull_request:
    branches:
      - '*'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2

jobs:
  # Install dependencies
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/install-cache
      - uses: ./.github/actions/turbo-cache
      - name: Install
        run: npm install --no-audit --no-fund

  # Build project
  build:
    name: Build
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/install-cache
      - uses: ./.github/actions/build-cache
      - uses: ./.github/actions/turbo-cache
      - name: Build
        run: |
          npx turbo run build --cache-dir=".turbo"

  # Code quality checks
  quality-checks:
    name: Lint
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/install-cache
      - uses: ./.github/actions/build-cache
      - uses: ./.github/actions/turbo-cache
      - name: Quality check
        run: |
          npx turbo run lint --cache-dir=".turbo"
          npx turbo run typecheck --cache-dir=".turbo"
      - name: Upload prisma client # to debug intermittent failures
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: prisma-client
          path: node_modules/.prisma/client

  # Unit tests
  unit-tests:
    name: Unit tests
    permissions: write-all
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/install-cache
      - uses: ./.github/actions/build-cache
      - uses: ./.github/actions/turbo-cache
      - name: Unit tests
        run: |
          npx turbo run test:ci --cache-dir=".turbo"
      - name: Upload prisma client # to debug intermittent failures
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: prisma-client
          path: node_modules/.prisma/client
      - name: Unit tests coverage comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          title: Unit tests coverage
          multiple-files: |
            Web App, apps/web/coverage/coverage-summary.json
            Ingest App, apps/ingest/coverage/coverage-summary.json
            UI Package, packages/ui/coverage/coverage-summary.json
            Email Package, packages/email/coverage/coverage-summary.json
            Auth Package, packages/auth/coverage/coverage-summary.json
